version: "3"
services: 
    app:
        container_name: vipinNODEJScontainerLOCAL
        restart: always
        build: .
        ports: 
            - "8080:8080"
        links: 
            - mongo
    mongo:
        container_name: vipinMONGOcontainer
        image: mongo
        ports: 
            -  "27018:27017"


